#!/bin/bash

echo "Installing homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install yadm fish gpg

yadm clone https://github.com/jackielii/dotfiles.git
