#!/bin/bash

echo "Installing homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install yadm gpg

export GIT_CONFIG_NOSYSTEM=1

echo "Cloning jackielii/dotfiles"
yadm clone https://github.com/jackielii/dotfiles.git
