#!/bin/bash
set -e

# Install using:
# /bin/bash -c "$(curl -fsSL https://jackieli.dev/dot)"

echo "Installing homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install yadm gpg

echo "Cloning jackielii/dotfiles"
yadm clone https://github.com/jackielii/dotfiles.git
