#!/bin/bash

set -e

echo "Installing homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install yadm gpg

echo "Run this in $HOME directory"

echo "Cloning jackielii/dotfiles"
yadm clone https://github.com/jackielii/dotfiles.git
